In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('data\\train.csv')
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
from sklearn import svm
from sklearn.model_selection import train_test_split
y = df['label']
X = df.drop('label',axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

svm_clf = svm.SVC(decision_function_shape='ovo')
svm_clf.fit(X_train, y_train)

SVC(decision_function_shape='ovo')

In [4]:
from sklearn.metrics import accuracy_score

y_pred = svm_clf.predict(X_test)

svm_accu = accuracy_score(y_test,y_pred)

In [5]:
y_pred

array([8, 1, 9, ..., 7, 4, 4])

In [6]:
print(svm_accu)

0.9740952380952381

# SVC submission

In [7]:
test_df = pd.read_csv('/content/test.csv')

test_pred = svm_clf.predict(test_df)

In [8]:
result_df = pd.DataFrame(test_pred,columns=['Label'])
result_df.index = result_df.index+1;
result_df.index.name = 'ImageId'
result_df.head()

         Label
ImageId
1            2
2            0
3            9
4            9
5            3

In [9]:
result_df.to_csv('submission.csv')

In [12]:
from sklearn.metrics import confusion_matrix
print("confusion_matrix imported")

confusion_matrix imported

In [14]:
y_pred = svm_clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1016    0    1    0    2    1    4    0    1    0]
 [   0 1139    1    0    1    1    0    1    2    1]
 [   4    4 1038    4    9    0    4    3    6    0]
 [   1    5    6 1106    0   10    0    6   11    6]
 [   1    0    3    0  997    1    6    3    0   13]
 [   1    1    1   11    2  870    7    0    2    3]
 [   6    2    1    0    0    1  996    0    4    0]
 [   0    5    7    1    6    1    0 1101    3   11]
 [   1    3    2    8    5    6    1    2  976    1]
 [   5    1    2   11   13    1    0    8    4  989]]